### ISSUE TITLE
question for login with Office 365

### ISSUE THREAD

**Issue by euglevi** [pdobsan/oama#31]
Hello, I am trying to authenticate my Office 365 account. I work at a company that requires a 2-step authentication with Microsoft Authenticator. With the mutt oauth2 script things are working fine, with mailctl I insert my password but then I receive the following message error I do not quite understand:

```
Request
    { requestMethod = "POST"
    , httpVersion = HTTP/1.1
    , rawPathInfo = "/common/login"
    , rawQueryString = ""
    , requestHeaders =
        [
            ( "Host"
            , "localhost:8080"
            )
        ,
            ( "User-Agent"
            , "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
            )
        ,
            ( "Accept"
            , "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
            )
        ,
            ( "Accept-Language"
            , "it,en-US;q=0.7,en;q=0.3"
            )
        ,
            ( "Accept-Encoding"
            , "gzip, deflate, br"
            )
        ,
            ( "Referer"
            , "http://localhost:8080/"
            )
        ,
            ( "Content-Type"
            , "application/x-www-form-urlencoded"
            )
        ,
            ( "Content-Length"
            , "1681"
            )
        ,
            ( "Origin"
            , "http://localhost:8080"
            )
        ,
            ( "DNT"
            , "1"
            )
        ,
            ( "Connection"
            , "keep-alive"
            )
        ,
            ( "Cookie"
            , "brcap=0; wlidperf=FR=L&ST=1700666960153; session=eyJjc3JmdG9rZW4iOiAiOTg2MTk3Njc2NiJ9.ZVzAKA.v-eECYYZjVnKU0Zns80l0DqI5x0; MicrosoftApplicationsTelemetryDeviceId=a0ed6817-3749-4531-ac6c-e0d16cc782f5; ai_session=AVdLwiRwpvBkqVgQgHILVf|1700666700871|1700666809099; MSFPC=GUID=6efa70116e464e1e89365f00ed644c72&HASH=6efa&LV=202311&V=4&LU=1700666703642"
            )
        ,
            ( "Upgrade-Insecure-Requests"
            , "1"
            )
        ,
            ( "Sec-Fetch-Dest"
            , "document"
            )
        ,
            ( "Sec-Fetch-Mode"
            , "navigate"
            )
        ,
            ( "Sec-Fetch-Site"
            , "same-origin"
            )
        ,
            ( "Sec-Fetch-User"
            , "?1"
            )
        ]
    , isSecure = False
    , remoteHost =
        [ ::1 ]:53512
    , pathInfo =
        [ "common"
        , "login"
        ]
    , queryString = []
    , requestBody = 
    , vault = 
    , requestBodyLength = KnownLength 1681
    , requestHeaderHost = Just "localhost:8080"
    , requestHeaderRange = Nothing
    }
```

For completeness, this is my services.yaml file:

```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: cd803c31-c6ae-4fc0-88d2-691631d49264
  client_secret: '-Xo8Q~YSCxDcmqmLDuzVGwvwKx8pXT9aHfVrRdu_'

```

Am I doing something wrong or is it just that mailctl does not work with certain organizations?

Thank you very much in advance.
