### ISSUE TITLE
Login to outlook account does not work

### ISSUE THREAD

**Issue by javiertury** [pdobsan/oama#33]
Running `mailctl authorize microsoft XXX@outlook.com` (with or without `--nohint`) and clicking "Next" in the login page produces the following error,

```
There was an issue looking up your account. Tap Next to try again.
```

which keeps appearing after clicking "Next".

If instead, I go to "Sign-In Options" and use the organization domain name `live.com`, I get the following error,

```
AADSTS50020: User account 'XXX@outlook.com' from identity provider 'live.com' does not exist in tenant '' and cannot access the application 'XXX' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
```

For reference, I'm using the following configuration where `client_id` and `client_secret` were copied from Thunderbird.

```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: XXX
  client_secret: XXX
```

This problem seems to affect personal/free outlook accounts only, but I can sign in just fine to organizational accounts.
