### ISSUE TITLE
mailctl trying to use wrong key for encryption

### ISSUE THREAD

**Issue by ferdinandyb** [pdobsan/oama#39]
I had an unfortunate mixup of configs between machines, so for a short time the below key was indeed set in the config file, but this is no longer the case. I actually outright removed the key, to make sure it's nowhere, yet still:

```
Authorization started ...
gpg: D92449B0F2D9363A2DE3260B207C0A2055199A65: skipped: No public key
gpg: [stdin]: encryption failed: No public key
```

```
❯ cat .config/mailctl/config.yaml
services_file: ~/.config/mailctl/services.yaml
oauth2_dir: ~/.local/var/mailctl
# This encryption method using gnupg.
# Alternatives like gnome-keyring can also be configured here.
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - 79768ABA7C3D9B56
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt
 ```

I tried deleting anything related to mailctl on the off-chance it is caching something, but at this point I am at a complete loss why it's doing this ... Any ideas?
