### ISSUE TITLE
invalid redirect URI for Microsoft

### ISSUE THREAD

**Issue by benasocj** [pdobsan/oama#44]
When running `oama authorize microsoft redacted@example.com` I get the following error when authorizing in the browser:
> Message: AADSTS50011: The redirect URI 'http://localhost:8080/finish' specified in the request does not match the redirect URIs configured for the application '08162f7c-0fd2-4200-a84a-f25a4db0b584'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Here the URL of the web page where the error is shown:
https://login.microsoftonline.com/efggraz.at/oauth2/v2.0/authorize?client_id=08162f7c-0fd2-4200-a84a-f25a4db0b584&redirect_uri=http%3a%2f%2flocalhost%3a8080%2ffinish&response_type=code&scope=https%3a%2f%2foutlook.office365.com%2fIMAP.AccessAsUser.All+https%3a%2f%2foutlook.office365.com%2fSMTP.Send+offline_access&login_hint=redacted%40example.com&allowbacktocommon=True

I'm using the `client_id` and `client_secret` from Thunderbird from [here](https://github.com/mozilla/releases-comm-central/blob/74e720e53831bb5f0e27a8d33a9c1d30846de30b/mailnews/base/src/OAuth2Providers.jsm#L129).

I just tested the same with `mailctl` and it works fine there.

I'm not sure if this is related to #43.

**Comment by pdobsan** [comment]
On Mon, May 13, 2024 at 04:02:37AM GMT, Benjamin Dopplinger wrote:
> I just tested the same with `mailctl` and it works fine there.

Please post your services.yaml file for mailctl.

> I'm not sure if this is related to #43.

Yes it is, read and follow it.

Is your microsoft account is also an organizational account?

**Comment by benasocj** [comment]
>Please post your services.yaml file for mailctl.

Here it is:
```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
  client_secret: "TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82"
```

>Is your microsoft account is also an organizational account?

Yes.
