### ISSUE TITLE
Microsoft service parameter 'redirect_uri' in oama ?

### ISSUE THREAD

**Issue by ArthurBorsboom** [pdobsan/oama#53]
The way I used ```mailctl``` was behind a proxy (https://sub.mydomain.com), which worked fine due to a microsoft service option ```redirect_uri``` to help with the response from Microsoft.

```oama printenv``` does not show this option.
A brave attempt to add ```redirect_uri``` in the config.yaml did not work either. :)

Manually changing the URL in the browser from http://localhost:8080 to the redirect URL results in a working result (oama received  the token).

Is this option or an alternative available?
If not, is there a plan to add it in the future?
Or am I making a mistake somewhere?

**Comment by pdobsan** [comment]
> The way I used `mailctl` was behind a proxy (https://sub.mydomain.com), which worked fine due to a microsoft service option `redirect_uri` to help with the response from Microsoft.

What was your mailctl services.yaml file?

> Manually changing the URL in the browser from http://localhost:8080 to the redirect URL results in a working result (oama received the token).

Interesting, how did this go in more details?

Once you have the refresh_token oama should work as usual for ever. So you need this trick only once.

> Is this option or an alternative available?

Not at the moment.

> If not, is there a plan to add it in the future?

Maybe, there is a dev branch for it. This  redirect_uri is much more complicated than it seems.
Keep in mind I don't have any kind of microsoft account.

**Comment by ArthurBorsboom** [comment]
> What was your mailctl services.yaml file?

```
[backup@xen1 mailctl]$ cat services.yaml 
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/xxxxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxx/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: https://web1-oauth.mydomain.com
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxx
```

> Interesting, how did this go in more details?

This option resulted in two differences, as far as I remember.
First the generated URL on the command line changed.

From:
```
[backup@xen1 mailctl]$ oama authorize microsoft xxxxxxxxxxxxx
To grant OAuth2 access to xxxxxxxxxxxxx visit the local URL below with your browser.
http://localhost:8080/start
Authorization started ...
````

to: 
```
[backup@xen1 mailctl]$ oama authorize microsoft xxxxxxxxxxxxx
To grant OAuth2 access to xxxxxxxxxxxxx visit the local URL below with your browser.
https://web1-oauth.mydomain.com/start
Authorization started ...
````

The example above is oama and contains some editing, but the essence is the same.
Once Microsoft returns a token, MS generates a redirect URL in the browser.

from:
```http://localhost:8080/?token&xxxxxxxxxxxx```

Which gives a HTTP 404, since this is a call on a remote server.

to:
```https://web1-oauth.mydomain.com/?token&xxxxxxxxxxxx```

The URLs above are fake, but the return URL is somewhat similar.

For this to work I have to make sure the redirect URL is on an allow list at Microsoft, i.e.
[Azure] > [App registration] > [Authentication] > [Web redirect URLs]

![Screenshot_2024-05-24_16-32](https://github.com/pdobsan/oama/assets/6639859/d4148adb-8e6b-4850-bca4-bbc35aa13bf7)

In the example above, I recently had to add http://localhost:8080 as a workaround, since oama always sends this as the redirect URL. But ideally, this should not be there (mess and security).

> Once you have the refresh_token oama should work as usual for ever. So you need this trick only once.

That is good to know. However, I vaguely recall in the past (the earlier versions of mailctl) used to 'lose' the (Microsoft) refresh token after a certain period. But I haven't been refreshing for quite a while, so I guess this is an issue of the past and got resolved.

> Keep in mind I don't have any kind of microsoft account.

I feel your pain. :)
That makes life harder and coding slower, but I can help with the testing.

Hopefully the source code of mailctl might give a clue.
As if you wouldn't have thought about that. :)
