### ISSUE TITLE
Error "key 'scope' not found"

### ISSUE THREAD

**Issue by OlMon** [pdobsan/oama#54]
Greetings,

Not sure what happened in the last couple updates.
But now I get the following error:

```
ERROR - Authorization failed.
localWebServer:
fetchAuthRecord: Error in $: parsing OAMa.Environment.AuthRecord(AuthRecord) failed, key "scope" not found
CallStack (from HasCallStack):
  error, called at lib/OAMa/Authorization.hs:386:21 in oama-0.13-inplace:OAMa.Authorization
```

I did update my config to include recent changes, but nothing helps.

config.yaml

```
## oama version 0.13

## This is a YAML configuration file, indentation matters.
## Double ## indicates comments while single # default values.
## Not all defaults are shown, for full list run `oama printenv`
## and look at the `services:` section.

## Possible options for keeping refresh and access tokens:
## GPG - in a gpg encrypted file ~/.local/var/oama/<email-address>.oauth
## GRING - in the default Gnome keyring
##
## Choose exactly one.

encryption:
    tag: GRING

# encryption:
#   tag: GPG
#   contents: your-KEY-ID

## Builtin service providers
## - google
## - microsoft
## Required fields: client_id, client_secret
##
services:
  google:
    client_id: application-CLIENT-ID
    client_secret: application-CLIENT-SECRET
  #  auth_scope: https://mail.google.com/
  #   redirect_uri: http://localhost:8080

  microsoft:
    client_id: <id of popular open-source mail client>
    client_secret: <secret of popular open-source mail client>
    auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All
      https://outlook.office365.com/SMTP.Send
      offline_access
    redirect_uri: http://localhost:8080
    tenant: common

  ## User configured providers
  ## Required fields: client_id, client_secret, auth_endpoint, auth_scope, token_endpoint
  ##
  ## For example:
  # yahoo:
  #   client_id: application-CLIENT-ID
  #   client_secret: application-CLIENT_SECRET
  #   auth_endpoint: EDIT-ME!
  #   auth_scope: EDIT-ME!
  #   token_endpoint: EDIT-ME!
  #   redirect_uri: http://localhost:8080
```

Cheers!

**Comment by OlMon** [comment]
Looking at the debug output I found the following:

```
{"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'grant_type'. Trace ID:
xxx Correlation ID: xxx Timestamp: 2024-05-27 10:31:13Z","error_codes":[9001
44],"timestamp":"2024-05-27 10:31:13Z","trace_id":"xxx","correlation_id":"xxx","error_uri":"https://login.microsoftonline.com/error?code=900144"}
```

**Comment by pdobsan** [comment]
On Mon, May 27, 2024 at 03:26:28AM GMT, OlMon wrote:
> But now I get the following error:
> 
> ```
> ERROR - Authorization failed.

What was the command?

Send the output of oama printenv.

**Comment by OlMon** [comment]
This happens while authorizing:
```
oama authorize microsoft <email>
```

```
###  Runtime environment  ###
config:
  encryption:
    tag: GRING
  redirect_port: 8080
  services:
    google:
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: application-CLIENT-ID
      client_secret: application-CLIENT-SECRET
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
    microsoft:
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
        offline_access
      client_id: <id>
      client_secret: <secret>
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/<user>/.config/oama/config.yaml
data_dir: /home/<user>/.local/var/oama
oama_version: '0.12'
op_sys: |
  Linux <user> 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: application-CLIENT-ID
    client_secret: application-CLIENT-SECRET
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
  microsoft:
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
      offline_access
    client_id: <id>
    client_secret: <secret>
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBody
######
```

**Comment by pdobsan** [comment]
> I jumped back to Version 1.10, that is the newest version that does not output this bug...

What version was that exactly? There is no such version you wrote here.

Apparently github does not send email about edits of comments, so I missed that.

**Comment by OlMon** [comment]
Sorry I wanted to write 0.11.1

**Comment by pdobsan** [comment]
Analyzing the changes after that version I  could not find a cause.
Any changes with the most recent release?

**Comment by OlMon** [comment]
Still getting the error, not really sure what is happening.
Can you tell me what I should delete to create a "clean" starting point. Then I will test more to find out what is happening.

**Comment by OlMon** [comment]
I have a setup to recreate the problem, I hope this is a valid test:

1. Create with secret tool a fake entry in gnome keyring:
```
secret-tool store --label "oama - test@test.com" "oama" "test@test.com"
```

2. Using seahorse I change the password to the following
```
{"access_token":"asd","email":{"unEmailAddress":"test@test.com"},"exp_date":"2024-05-29 19:26 UTC","expires_in":3897,"refresh_token":"asdasdasd","scope":"https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send","service":"microsoft","token_type":"Bearer"}
```

3. Create following config in ~/.config/oama [I understand there are a lot of comments, but I leave it as is]
```
## oama version 0.13.1

## This is a YAML configuration file, indentation matters.
## Double ## indicates comments while single # default values.
## Not all defaults are shown, for full list run `oama printenv`
## and look at the `services:` section.

## Possible options for keeping refresh and access tokens:
## GPG - in a gpg encrypted file ~/.local/var/oama/<email-address>.oauth
## GRING - in the default Gnome keyring
##
## Choose exactly one.

encryption:
    tag: GRING

# encryption:
#   tag: GPG
#   contents: your-KEY-ID

## Builtin service providers
## - google
## - microsoft
## Required fields: client_id, client_secret
##
services:
  google:
    client_id: application-CLIENT-ID
    client_secret: application-CLIENT-SECRET
  #  auth_scope: https://mail.google.com/

  microsoft:
    client_id: application-CLIENT-ID
    client_secret: application-CLIENT_SECRET
    auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All
      https://outlook.office365.com/SMTP.Send
      offline_access
    tenant: common

  ## User configured providers
  ## Required fields: client_id, client_secret, auth_endpoint, auth_scope, token_endpoint
  ##
  ## For example:
  # yahoo:
  #   client_id: application-CLIENT-ID
  #   client_secret: application-CLIENT_SECRET
  #   auth_endpoint: EDIT-ME!
  #   auth_scope: EDIT-ME!
  #   token_endpoint: EDIT-ME!
```

5. Call renew
```
oama renew test@test.com
```

6. Get following error
```
{"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'grant_type'. Trace ID: 288138d7-e23d-46f0-b860-079c7ecd3700 Correlation ID: 20360649-b186-458a-8bc7-5fa836bc3679 Timestamp: 2024-05-29 18:53:51Z","error_codes":[900144],"timestamp":"2024-05-29 18:53:51Z","trace_id":"288138d7-e23d-46f0-b860-079c7ecd3700","correlation_id":"20360649-b186-458a-8bc7-5fa836bc3679","error_uri":"https://login.microsoftonline.com/error?code=900144"}
oama: fetchAuthRecord: Error in $: parsing OAMa.Environment.AuthRecord(AuthRecord) failed, key "scope" not found
CallStack (from HasCallStack):
  error, called at lib/OAMa/Authorization.hs:242:19 in oama-0.13.1-inplace:OAMa.Authorization
```


This is the same error what I get when I try to authorize a new key with the newer versions. So I hope this helps in some way. Unless I did something wrong for the test, that let me know I will try more stuff.

**Comment by pdobsan** [comment]
On Wed, May 29, 2024 at 11:59:25AM GMT, OlMon wrote:
> I have a setup to recreate the problem, I hope this is a valid test:
> 
> 1. Create with secret tool a fake entry in gnome keyring:

Almost, but the scope left out the `offline_access`, the most important
part. -- don't ask why or what its name really means.

> 3. Create following config in ~/.config/oama [I understand there are a
> lot of comments, but I leave it as is]

The config is not so important what is always important the output of
`printenv` it shows the config and how the program parsed and
interpreted it. I invented this direct for debugging problem reporting.

Anyway, I would advise you to create a separate config file for
debugging, you can specify it by `oama -c debug-conf.yaml ...` and in
that use the gpg encrypted method to keep the credentials. For debugging
use always the **most recent version only**. No need to create fake
account, use it with a real one. And always send the printenv and the
crash messages.

This way you can keep the older version which works for you in
production while experimenting with the new ones. They won't interfere
with each other.

**Comment by gilcu3** [comment]
I am getting this issue as well. I have to machines that were previously using `mailctl` and now use `oama`. In one of them the transition went without issues, in the other one this error. Configuration is the same. The difference is that probably the token for the machine that was failing expired. Is there any way to help fixing this?

**Comment by pdobsan** [comment]
On Fri, May 31, 2024 at 06:25:49AM GMT, gilcu3 wrote:
> The difference is that probably the token for the machine that was
> failing expired.

What token?

> Is there any way to help fixing this?

Maybe, by following the guidelines on how to report an error:
https://github.com/pdobsan/oama#issues

In your case, providing the same kind of information both for the
working and failing machine could be useful.

**Comment by gilcu3** [comment]
> On Fri, May 31, 2024 at 06:25:49AM GMT, gilcu3 wrote: The difference is that probably the token for the machine that was failing expired.
> What token?
> Is there any way to help fixing this?
> Maybe, by following the guidelines on how to report an error: https://github.com/pdobsan/oama#issues In your case, providing the same kind of information both for the working and failing machine could be useful.

Alright:

For current version:
```
❯ oama printenv
###  Runtime environment  ###
config:
  encryption:
    contents: --
    tag: GPG
    microsoft:
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
        offline_access
      client_id: --
      client_secret: --
      redirect_uri: null
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/--/.config/oama/config.yaml
data_dir: /home/--/.local/var/oama
oama_version: 0.13.1
op_sys: |
  Linux -- 6.9.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  microsoft:
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
      offline_access
    client_id: --
    client_secret: --
    redirect_uri: null
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBody
######
```
```
❯ oama access myemail@domain
{"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'grant_type'. Trace ID: -- Correlation ID: -- Timestamp: 2024-05-31 16:54:41Z","error_codes":[900144],"timestamp":"2024-05-31 16:54:41Z","trace_id":"--","correlation_id":"--","error_uri":"https://login.microsoftonline.com/error?code=900144"}
oama: getEmailAuth:
fetchAuthRecord: Error in $: parsing OAMa.Environment.AuthRecord(AuthRecord) failed, key "scope" not found
CallStack (from HasCallStack):
  error, called at lib/OAMa/Authorization.hs:137:22 in oama-0.13.1-inplace:OAMa.Authorization
```


Same machine, after downgrading to `0.11.1`:
```
❯ oama printenv
###  Runtime environment  ###
config:
  encryption:
    contents: --
    tag: GPG
  redirect_port: 8080
  services:
    microsoft:
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
        offline_access
      client_id: --
      client_secret: --
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/--/.config/oama/config.yaml
data_dir: /home/--/.local/var/oama
oama_version: 0.11.1
op_sys: |
  Linux -- 6.9.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  microsoft:
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send
      offline_access
    client_id: --
    client_secret: --
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBodyForm
######
```
```
❯ oama access myemail@domain
my access token
```
I am using `client_id` and `client_secret` available online, and the account is microsoft/institutional.
