### ISSUE TITLE
Can't authorize google

### ISSUE THREAD

**Issue by kflak** [pdobsan/oama#58]
Hi,

I am getting this when running `oama authorize google <my.email@my.university>` which is hosted by our dear friends google:

```
400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
```

My configuration:
```
## oama version 0.14

encryption:
    tag: GPG
    contents: "~/.ssh/id_rsa.pub"

services:
  google:
    client_id: 406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com
    client_secret: kSmqreRr0qwBWJgbf5Y-PjSU
  #  auth_scope: https://mail.google.com/

```

Grateful for any pointers as to why this happens! Running on Arch Linux 6.9.8.

EDIT: Trying with my personal gmail account, and I'm getting a bit further. The process now stalls at the gpg stage:

```
❯ oama authorize google myemail@gmail.com
Authorization to grant OAuth2 access to myemail@gmail.com started ... 
Visit http://localhost:53919/start in your browser ...
gpg: ~/.ssh/id_rsa.pub: skipped: No public key
gpg: [stdin]: encryption failed: No public key
ExitFailure 2
```
Which seems to indicate that I am probably an idiot that doesn't know how to juggle gpg keys. I tried a couple of different versions, with the same result: pasting the contents of id_rsa.pub into the `content` key delivered the same result. So, yeah, I guess I need a bit of handholding here...
