### ISSUE TITLE
feature request: option to specify location of gpg encrypted file

### ISSUE THREAD

**Issue by newhallroad** [pdobsan/oama#61]
Thanks for an excellent project.

I am running oama on a Windows 10 machine inside WSL2. It would be helpful if there was an option to be able to specify the location of the gpg encrypted file. 

**Longer explanation**

oama works perfectly inside WSL2. But I would also like to access it from windows as a wsl binary. However, the windows system doesn't recognize the internal path. Thus, from _inside_ a WSL terminal (Ubuntu in my case), `oama access user@gmail.com` works perfectly. But from the Windows cmd cli, I get the following:

```
$ C:\Users\user>wsl oama access user@gmail.com
gpg: can't open '/home/user/.local/var/oama/user@gmail.com.oama': No such file or directory
gpg: decrypt_message failed: No such file or directory
```

I believe that if I could store the encrypted file on the windows filesystem and specify the path to oama, then it would work both from within WSL and from the Windows cli. 

The reason I want this is to be able to send email from inside Gnu emacs for Windows by integrating oama with msmtp. But this can only be done if emacs can run oama via WSL2.

I understand if this might be too niche a requirement to bother working on, but if you were willing to consider it, I would be very grateful. Or, if you have any other suggestions for a work around, that would also be great. (I have been wondering about using cross-platform password managers but my experimentations have not been successful. I am pretty new at this so I might be missing some ideas.)

In any case, thank you very much for all of your generous contributions to the community and for this excellent project.

**my printenv**
```
###  Runtime environment  ###
config:
  encryption:
    contents: <GPG_key_id>
    tag: GPG
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: <client_id>
      client_secret: <client_secret>
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/user/.config/oama/config.yaml
data_dir: /home/user/.local/var/oama
oama_version: '0.14'
op_sys: |
  Linux MACHINE_NAME 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: <client_id>
    client_secret: <client_secret>
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
######
```
