### ISSUE TITLE
oama seems to encrypt to multiple keys?

### ISSUE THREAD

**Issue by ferdinandyb** [pdobsan/oama#69]
I have 

```yml
encryption:
  tag: GPG
  contents: 79768ABA7C3D9B56 #not my yubikey
```

in my config.yaml, but if I go `gpg --list-packets priestoferis@gmail.com.oama` there are two keys listed there, my yubikey and something I just have locally. Now the default one is my yubikey, so `access` always tries to decrypt with that first, either waiting for me to touch the key, or prompting me to insert it. If the key is not in the machine and I cancel the insert prompt then the file is still decrypted. Did I misunderstand the config for how to tie output file to a single key? Having it also encrypted to my yubikey not very convenient in automated processes.
