### ISSUE TITLE
Error "key 'scope' not found" (seems to be the same as closed issue #54)

### ISSUE THREAD

**Issue by SammyJenas** [pdobsan/oama#72]
> Hi,
> I seem to be encountering this problem with Oama version 0.16-6:
> 
> ```
> oama: getEmailAuth:
> fetchAuthRecord: Error in $: parsing OAMa.Environment.AuthRecord(AuthRecord) failed, key "scope" not found
> CallStack (from HasCallStack):
>   error, called at lib/oama/OAMa/Authorization.hs:123:22 in oama-0.16-inplace:OAMa.Authorization
>  ``` 

 _Originally posted by @SammyJenas in [#54](https://github.com/pdobsan/oama/issues/54#issuecomment-2646816115)_

Here is the output of oama printenv:

```
###  Runtime environment  ###
config:
  encryption:
    tag: KEYRING
  services:
    microsoft:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
        offline_access
      client_id: <found online>
      client_secret: <found online>
      prompt: null
      redirect_uri: null
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/sammy/.config/oama/config.yaml
oama_version: '0.16'
op_sys: |
  Linux linuxarchfile 6.13.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Feb 2025 22:24:02 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  microsoft:
    access_type: null
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
      offline_access
    client_id: <found online>
    client_secret: <found online>
    prompt: null
    redirect_uri: null
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBodyForm
state_dir: /home/sammy/.local/state/oama
######
```
