### ISSUE TITLE
Can't generate Access/Refresh token for personal Outlook account

### ISSUE THREAD

**Issue by relma2** [pdobsan/oama#73]
I'm trying to replicate how Mailspring generates a Refresh/Access token from Outlook credential, and it looks like they don't use a client secret but rather a "challenge" and this allows personal Outlook accounts.

How do I put a "code challenge" in Oama to replicate this?

---

To clarify: what I want to do is to be able to authenticate with my personal Outlook/Hotmail account and recieve a refresh/access token from it. My config file looks like this, and I am running in circles:
```
services
  outlook:
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: offline_access
     user.read
    client_id: XXX
    client_secret: XXX # Are we not supposed to use this??
```

**Comment by keithbowes** [comment]
I was just trying to authorize my Hotmail account but it kept giving me an error about an invalid scope. I ultimately changed `auth_scope` to `scope` in config.yaml and it worked fine. Maybe that will also solve your problem.

**Comment by AlexanderTheGrey** [comment]
@keithbowes Can you post your `config.yaml`?

How did you get the `redirect_uri` working correctly with Microsoft?

**Comment by pdobsan** [comment]
On Sat, Mar 22, 2025 at 11:15:50PM -0700, AlexanderTheGrey wrote:
> @keithbowes Can you post your `config.yaml`?

Instead, both of you, please post the output of the command

    oama printenv

**Comment by AlexanderTheGrey** [comment]
Here's mine:

<details>
  <summary><code>oama printenv</code></summary>

```yaml
###  Runtime environment  ###
config:
  encryption:
    tag: KEYRING
  services:
    microsoft:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
        offline_access
      client_id: 9e5f94bc-e8a4-4e73-b8be-63364c29d753
      client_secret: ''
      prompt: null
      redirect_uri: null
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /root/.config/oama/config.yaml
oama_version: '0.18'
op_sys: |
  Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  microsoft:
    access_type: null
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
      offline_access
    client_id: 9e5f94bc-e8a4-4e73-b8be-63364c29d753
    client_secret: ''
    prompt: null
    redirect_uri: null
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBodyForm
state_dir: /root/.local/state/oama
######
```
</details>

Keep in mind that when I add the `redirect_uri` used in `mutt_oauth2.py`:

```yaml
redirect_uri: https://login.microsoftonline.com/common/oauth2/nativeclient
```

I get this error:

```
Authorization to grant OAuth2 access to example@hotmail.com started ... 
oama: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

Prelude.read: no parse
oama: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

Prelude.read: no parse
```
