### ISSUE TITLE
oama: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.IOException

### ISSUE THREAD

**Issue by akNG71** [pdobsan/oama#77]
Output of `oama printenv`:
```
### Secret Management Method: secret-tools
###  Runtime environment  ###
config:
  encryption:
    tag: KEYRING
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://mail.google.com/
      client_id: <client_id>
      client_secret: <client_secret>
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/arunkhattri/.config/oama/config.yaml
oama_version: 0.19.0
op_sys: |
  Linux nakedgun 6.14.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 07 Apr 2025 19:59:13 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: <client_id>
    client_secret: <client_secret>
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
state_dir: /home/arunkhattri/.local/state/oama
######
```
command `oama authorize google arunkhattri@gmail.com --nohint` resulting in an error -

```
oama: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.IOException:

Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: "localhost", service name: "35921"): does not exist (Name does not resolve)

HasCallStack backtrace:
  ioError, called at Network/Socket/Info.hsc:287:13 in network-3.2.7.0-9c65ee37c8c6922ad2dce3cd8c4986317c253a4dc31b742635793c07dd4e7ebe:Network.Socket.Info

oama: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.BlockedIndefinitelyOnMVar:

thread blocked indefinitely in an MVar operation
```

It's a personal google account, On days it runs without error, however last 3/4 weeks i was encountering this error frequently, and for the last 4 days it's not buzzing and not able to use isync.
