### ISSUE TITLE
Unable to authorize Google

### ISSUE THREAD

**Issue by honza** [pdobsan/oama#78]
I'm using the precompiled binary of 0.19.

I created my own OAuth app in Google Cloud.  I'm using a Google Workplace account (Gmail on my own domain).  The app is set to external and the credentials are of the desktop kind. I added the `https://mail.google.com/` scope.

I run:

```
$ oama authorize google <email address>
```

The local server starts and I follow the link.  Google finds my OAuth app and asks me to select an account and to authorize the app.  I click allow and then Google says an unknown error has occurred and to try again.  No errors in the Google Cloud console.  Running oama with `--debug` doesn't show any errors. 

Is this a common issue?  Do I need to configure something special on Google's side?

Any hints would be appreciated!

```
### Secret Management Method: secret-tools
###  Runtime environment  ###
config:
  encryption:
    contents: '0xFFBD...'
    tag: GPG
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: <google>
      client_secret: <google>
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/user/.config/oama/config.yaml
oama_version: 0.19.0
op_sys: |
  Linux donkey 6.12.21 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 28 21:03:33 UTC 2025 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: true
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: <google>
    client_secret: <google>
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
state_dir: /home/user/.local/state/oama
######
```
