### ISSUE TITLE
authorizeEmail: Unknown "ConnectionTimeout" when attempting to authorize

### ISSUE THREAD

**Issue by catniptwinz** [pdobsan/oama#79]
Using AUR package `oama-bin 0.19.0-1`. I'm finally migrating from mailctl, or at least attempting to.

Trying to authorize a personal GMail account, but am unable to connect to the local server. After some time, `oama authorize google <my address>` throws:

```
Authorization to grant OAuth2 access to <my address> started ...
Visit http://localhost:46547/start in your browser ...
oama: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

localWebServer:
ConnectionTimeout

HasCallStack backtrace:
  error, called at lib/OAMa/Authorization.hs:419:22 in oama-0.19.0-inplace:OAMa.Authorization

oama: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.BlockedIndefinitelyOnMVar:

thread blocked indefinitely in an MVar operation
```

Output of `oama printenv`:

```
### Secret Management Method: secret-tools
###  Runtime environment  ###
config:
  encryption:
    tag: KEYRING
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: <my client id>
      client_secret: <my client secret>
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/<my username>/.config/oama/config.yaml
oama_version: 0.19.0
op_sys: |
  Linux <my hostname> 6.13.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 23 Mar 2025 17:17:30 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: <my client id>
    client_secret: <my client secret>
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
state_dir: /home/<my username>/.local/state/oama
######
```

I see the same error if I explicitly define a service with all fields having the same values as in my prior (working) mailctl config rather than using the built-in "google" service.
