### ISSUE TITLE
GPG encryption failed cause of invalid path

### ISSUE THREAD

**Issue by stacyharper** [pdobsan/oama#80]
Hey there,

I'm trying to switch to `encryption: GPG`, but it fails while storing the tokens apparently:

```
Authorization to grant OAuth2 access to xxx.xxx@xxx.fr started ... 
Visit http://localhost:39437/start in your browser ...
FileError "Can't open file: /home/willow/.local/state/oama/xxx.xxx@xxx.fr.oama\n"
ExitFailure 1
```

env:

```
###  Runtime environment  ###
config:
  encryption:
    contents: XXX
    tag: GPG
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: xxx
      client_secret: xxx
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/willow/.config/oama/config.yaml
oama_version: '0.18'
op_sys: |
  Linux grey-bee 6.12.23-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2025-04-16 07:53:55 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: xxx
    client_secret: xxx
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
state_dir: /home/willow/.local/state/oama
######
```

**Comment by pdobsan** [comment]
On Sat Apr 19, 2025 at 7:00 AM CEST, Willow wrote:
> stacyharper created an issue (pdobsan/oama#80)
> I'm trying to switch to `encryption: GPG`, but it fails while storing the tokens apparently:
>
> ```
> Authorization to grant OAuth2 access to ***@***.*** started ... 
> Visit http://localhost:39437/start in your browser ...
> FileError "Can't open file: ***@***.***\n"
> ExitFailure 1
> ```

I can't reproduce that, works for me. Maybe it is a file permission error.
	
> config_file: /home/willow/.config/oama/config.yaml
> oama_version: '0.18'
> op_sys: |
>   Linux grey-bee 6.12.23-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2025-04-16 07:53:55 x86_64 GNU/Linux

You are not using the most recent version.
The released prebuilt executable should run fine on Alpine.

**Comment by stacyharper** [comment]
No, I can touch those files. I still reproduce using the pre-built binaries:

```
### Secret Management Method: secret-tools
###  Runtime environment  ###
config:
  encryption:
    contents: xxx
    tag: GPG
  services:
    google:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: null
      client_id: xxx
      client_secret: xxx
      prompt: null
      redirect_uri: null
      tenant: null
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/stacy/.config/oama/config.yaml
oama_version: 0.19.0
op_sys: |
  Linux yellow-orcess 6.14.2-0-edge #1-Alpine SMP PREEMPT_DYNAMIC Sat, 12 Apr 2025 16:09:57 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  google:
    access_type: offline
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    auth_scope: https://mail.google.com/
    client_id: xxx
    client_secret: xxx
    prompt: consent
    redirect_uri: null
    tenant: null
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: RequestBody
state_dir: /home/stacy/.local/state/oama
######
```
