### ISSUE TITLE
Unkown "Error in $.error..." — issue with oama authorize & Microsoft

### ISSUE THREAD

**Issue by SammyJenas** [pdobsan/oama#86]
I previously had Oama working with a university Microsoft account. My access token has now expired and I can't seem to get `oama authorize` to work in order to refresh the token.

If I do `oama authorize microsoft <my-email-address>` I'm sent to the browser for authorization, but the oama process doesn't complete after this.

Using `oama authorize microsoft <my-email-address> --device` the oama process completes with this error:
```
oama: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

authorizeEmail:
Unknown "Error in $.error: parsing OAMa.Environment.AuthError failed, expected tag field to be one of [\"invalid_grant\",\"invalid_request\",\"unauthorized_client\",\"access_denied\",\"unsupported_response_type\",\"invalid_scope\",\"server_error\",\"temporarily_unavailable\",\"authorization_pending\",\"slow_down\",\"expired_token\",\"unknown\"], but found tag \"invalid_client\""

HasCallStack backtrace:
  error, called at lib/OAMa/Authorization.hs:496:25 in oama-0.20.0-inplace:OAMa.Authorization
```

This is the output of `oama printenv`
```
### Secret Management Method: secret-tools
###  Runtime environment  ###
config:
  encryption:
    tag: KEYRING
  services:
    microsoft:
      access_type: null
      auth_endpoint: null
      auth_http_method: null
      auth_params_mode: null
      auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
        offline_access
      client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
      client_id_cmd: null
      client_secret: TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82
      client_secret_cmd: null
      prompt: null
      redirect_uri: null
      tenant: common
      token_endpoint: null
      token_http_method: null
      token_params_mode: null
config_file: /home/sammy/.config/oama/config.yaml
oama_version: 0.20.0
op_sys: |
  Linux linuxarchfile 6.14.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000 x86_64 GNU/Linux
options:
  optCommand:
    tag: PrintEnv
  optConfig: ~/.config/oama/config.yaml
  optDebug: false
services:
  microsoft:
    access_type: null
    auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
    auth_http_method: GET
    auth_params_mode: QueryString
    auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send
      offline_access
    client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
    client_id_cmd: null
    client_secret: TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82
    client_secret_cmd: null
    prompt: null
    redirect_uri: null
    tenant: common
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    token_http_method: POST
    token_params_mode: RequestBodyForm
state_dir: /home/sammy/.local/state/oama
######
```

In case these are useful: my [msmtp config](https://github.com/leverarchfile/dotfiles/blob/main/config/msmtp/config) and my [mbsync config](https://github.com/leverarchfile/dotfiles/blob/main/config/mbsync/config).
